---
name: build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #otp_vsn: [22.0, 22.1, 22.2, 22.3,
        #          23.0, 23.1, 23.2, 23.3,
        #          24.0]
        #os: [ubuntu-latest, windows-2019]
        otp_vsn: [24.0]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.16'
      - run: make test check RUNNING_ON_CI=yes
