---
name: build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: ['22.3', '23.3', '24.3', '25.2']
        os: ['ubuntu-20.04', 'windows-2019']
        rebar3_vsn: ['3.18', '3.20']
        exclude:
          - rebar3_vsn: '3.20'
            otp_vsn: '22.3'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.3'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.3'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.2'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.15.1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - run: make test check
